assets:
  credentials: yegor256/home#assets/eoc/credentials
install: |
  curl https://sh.rustup.rs -sSf | bash -s -- -y
  rustup toolchain install stable
  cargo -version
  pdd --file=/dev/null
merge:
  script: |
    cargo test
deploy:
  script: |
    cargo test
release:
  script: |-
    sed -i -e 's/^version = .*/version = "${tag}"/' Cargo.toml
    git commit -am "${tag}"
    cargo test
    cargo publish
