architect:
  - yegor256
docker:
  image: yegor256/rultor-image:1.9.1
assets:
  credentials: yegor256/objectionary-secrets#crates-credentials
install: |
  curl https://sh.rustup.rs -sSf | bash -s -- -y
  export PATH=$HOME/.cargo/bin:$PATH
  rustup toolchain install stable
  cargo --version
  pdd --file=/dev/null
merge:
  script: |
    cargo test --color=never
release:
  script: |-
    sed -i -e "s/^version = \"0.0.0\"/version = \"${tag}\"/" Cargo.toml
    cargo test --color=never
    git commit -am "${tag}"
    mkdir -p ~/.cargo && cp ../crates-credentials ~/.cargo
    cargo publish --color=never
