assets:
  credentials: yegor256/home#assets/eoc/credentials
install: |
  curl https://sh.rustup.rs -sSf | bash -s -- -y
  export PATH=$HOME/.cargo/bin:$PATH
  rustup toolchain install stable
  cargo --version
  pdd --file=/dev/null
merge:
  script: |
    cargo test
deploy:
  script: |
    cargo test
release:
  script: |-
    sed -i -e "s/^version = \"0.0.0\"/version = \"${tag}\"/" Cargo.toml
    git commit -am "${tag}"
    cargo test
    mkdir -p ~/.cargo && cp ../credentials ~/.cargo
    cargo publish
