[package]
name = "eoc"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.5.4"
lazy_static = "1.4.0"
rstest = "0.12.0"
assert_cmd = "2.0.4"
hex = "0.4.3"
strum = "0.23.0"
strum_macros = "0.23.1"
itertools = "0.10.3"
arr_macro = "0.1.3"
